### ISSUE TITLE
lib/x86/libandroid_platform.so: has text relocations

### ISSUE THREAD

**Issue by namratadakua** [Microsoft/Cognitive-Speech-STT-Android#12]
I am getting below error while invoking SpeechRecognitionServiceFactory.createMicrophoneClientWithIntent

with   compile 'com.microsoft.projectoxford:speechrecognition:1.+'

**Stack Trace:**
lib/x86/libandroid_platform.so: has text relocations
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.nkalucharandakua.myapplication, PID: 23286
                  java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.nkalucharandakua.myapplication-1/lib/x86/libandroid_platform.so: has text relocations
                      at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at com.microsoft.bing.speech.Conversation.<clinit>(Conversation.java:68)
                      at com.microsoft.cognitiveservices.speechrecognition.SpeechRecognitionServiceFactory.createMicrophoneClientWithIntent(SpeechRecognitionServiceFactory.java:1043)
                      at com.example.nkalucharandakua.myapplication.MainActivity.StartButton_Click(MainActivity.java:195)
                      at com.example.nkalucharandakua.myapplication.MainActivity.access$000(MainActivity.java:27)
                      at com.example.nkalucharandakua.myapplication.MainActivity$1.onClick(MainActivity.java:145)
                      at android.view.View.performClick(View.java:5610)
                      at android.view.View$PerformClick.run(View.java:22260)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Application terminated.

**Comment by polaris0227** [comment]
Hi @namratadakua .
I've got same error.
Did you resolve this issue.
If so, please share with me.
Regards.

**Comment by namratadakua** [comment]
Hi,

Not yet.. but still trying..

**Comment by polaris0227** [comment]
Thanks for your reply.

**Comment by jasonvomsft** [comment]
Please make sure you have targetSdkVersion set to 22.  The native JNI libraries do not fully support SDK versions >= 23+
